language: java
jdk:
  - oraclejdk9
install:
  - mvn validate
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.organization=petercipov-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN